# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_sharedbookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedbookmark',
            name='bookmark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarks.Bookmark'),
        ),
    ]
